# NOTE: A worker can only belong to one group.
# If multiple group's address (IPs, Domains) pattern matches
# to the worker's address, the worker will belong to the first group.

[A]
IPs = ["127.0.0.1"]
Domains = ["localhost"]
ServeTargets = ["*"]

[B]
IPs = ["192.168.*.*"]
Domains = ["*.imagvfx.com"]
ServeTargets = ["2d"]

